/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MediaRouteImport } from './routes/_media'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as MediaIndexRouteImport } from './routes/_media/index'
import { Route as MediaAboutRouteImport } from './routes/_media/about'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardGeneralRouteImport } from './routes/dashboard/general'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as SetupLibrariesRouteImport } from './routes/setup/libraries'
import { Route as SetupProfileRouteImport } from './routes/setup/profile'
import { Route as MediaLibrariesLibIdRouteImport } from './routes/_media/libraries/$libId'
import { Route as DashboardManageLibrariesRouteImport } from './routes/dashboard/manage.libraries'
import { Route as DashboardManageProfilesRouteImport } from './routes/dashboard/manage.profiles'

const MediaRoute = MediaRouteImport.update({
  id: '/_media',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaRoute,
} as any)
const MediaAboutRoute = MediaAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MediaRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGeneralRoute = DashboardGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => DashboardRoute,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const SetupLibrariesRoute = SetupLibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => SetupRoute,
} as any)
const SetupProfileRoute = SetupProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SetupRoute,
} as any)
const MediaLibrariesLibIdRoute = MediaLibrariesLibIdRouteImport.update({
  id: '/libraries/$libId',
  path: '/libraries/$libId',
  getParentRoute: () => MediaRoute,
} as any)
const DashboardManageLibrariesRoute =
  DashboardManageLibrariesRouteImport.update({
    id: '/manage/libraries',
    path: '/manage/libraries',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardManageProfilesRoute = DashboardManageProfilesRouteImport.update({
  id: '/manage/profiles',
  path: '/manage/profiles',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MediaIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/setup': typeof SetupRouteWithChildren
  '/about': typeof MediaAboutRoute
  '/dashboard/general': typeof DashboardGeneralRoute
  '/setup/libraries': typeof SetupLibrariesRoute
  '/setup/profile': typeof SetupProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/libraries/$libId': typeof MediaLibrariesLibIdRoute
  '/dashboard/manage/libraries': typeof DashboardManageLibrariesRoute
  '/dashboard/manage/profiles': typeof DashboardManageProfilesRoute
}
export interface FileRoutesByTo {
  '/about': typeof MediaAboutRoute
  '/dashboard/general': typeof DashboardGeneralRoute
  '/setup/libraries': typeof SetupLibrariesRoute
  '/setup/profile': typeof SetupProfileRoute
  '/': typeof MediaIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/setup': typeof SetupIndexRoute
  '/libraries/$libId': typeof MediaLibrariesLibIdRoute
  '/dashboard/manage/libraries': typeof DashboardManageLibrariesRoute
  '/dashboard/manage/profiles': typeof DashboardManageProfilesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_media': typeof MediaRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/setup': typeof SetupRouteWithChildren
  '/_media/about': typeof MediaAboutRoute
  '/dashboard/general': typeof DashboardGeneralRoute
  '/setup/libraries': typeof SetupLibrariesRoute
  '/setup/profile': typeof SetupProfileRoute
  '/_media/': typeof MediaIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/_media/libraries/$libId': typeof MediaLibrariesLibIdRoute
  '/dashboard/manage/libraries': typeof DashboardManageLibrariesRoute
  '/dashboard/manage/profiles': typeof DashboardManageProfilesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/setup'
    | '/about'
    | '/dashboard/general'
    | '/setup/libraries'
    | '/setup/profile'
    | '/dashboard/'
    | '/setup/'
    | '/libraries/$libId'
    | '/dashboard/manage/libraries'
    | '/dashboard/manage/profiles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/dashboard/general'
    | '/setup/libraries'
    | '/setup/profile'
    | '/'
    | '/dashboard'
    | '/setup'
    | '/libraries/$libId'
    | '/dashboard/manage/libraries'
    | '/dashboard/manage/profiles'
  id:
    | '__root__'
    | '/_media'
    | '/dashboard'
    | '/setup'
    | '/_media/about'
    | '/dashboard/general'
    | '/setup/libraries'
    | '/setup/profile'
    | '/_media/'
    | '/dashboard/'
    | '/setup/'
    | '/_media/libraries/$libId'
    | '/dashboard/manage/libraries'
    | '/dashboard/manage/profiles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MediaRoute: typeof MediaRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  SetupRoute: typeof SetupRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_media': {
      id: '/_media'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_media/': {
      id: '/_media/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof MediaRoute
    }
    '/_media/about': {
      id: '/_media/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MediaAboutRouteImport
      parentRoute: typeof MediaRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/general': {
      id: '/dashboard/general'
      path: '/general'
      fullPath: '/dashboard/general'
      preLoaderRoute: typeof DashboardGeneralRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/libraries': {
      id: '/setup/libraries'
      path: '/libraries'
      fullPath: '/setup/libraries'
      preLoaderRoute: typeof SetupLibrariesRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/profile': {
      id: '/setup/profile'
      path: '/profile'
      fullPath: '/setup/profile'
      preLoaderRoute: typeof SetupProfileRouteImport
      parentRoute: typeof SetupRoute
    }
    '/_media/libraries/$libId': {
      id: '/_media/libraries/$libId'
      path: '/libraries/$libId'
      fullPath: '/libraries/$libId'
      preLoaderRoute: typeof MediaLibrariesLibIdRouteImport
      parentRoute: typeof MediaRoute
    }
    '/dashboard/manage/libraries': {
      id: '/dashboard/manage/libraries'
      path: '/manage/libraries'
      fullPath: '/dashboard/manage/libraries'
      preLoaderRoute: typeof DashboardManageLibrariesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/manage/profiles': {
      id: '/dashboard/manage/profiles'
      path: '/manage/profiles'
      fullPath: '/dashboard/manage/profiles'
      preLoaderRoute: typeof DashboardManageProfilesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface MediaRouteChildren {
  MediaAboutRoute: typeof MediaAboutRoute
  MediaIndexRoute: typeof MediaIndexRoute
  MediaLibrariesLibIdRoute: typeof MediaLibrariesLibIdRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaAboutRoute: MediaAboutRoute,
  MediaIndexRoute: MediaIndexRoute,
  MediaLibrariesLibIdRoute: MediaLibrariesLibIdRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

interface DashboardRouteChildren {
  DashboardGeneralRoute: typeof DashboardGeneralRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardManageLibrariesRoute: typeof DashboardManageLibrariesRoute
  DashboardManageProfilesRoute: typeof DashboardManageProfilesRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGeneralRoute: DashboardGeneralRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardManageLibrariesRoute: DashboardManageLibrariesRoute,
  DashboardManageProfilesRoute: DashboardManageProfilesRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SetupRouteChildren {
  SetupLibrariesRoute: typeof SetupLibrariesRoute
  SetupProfileRoute: typeof SetupProfileRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupLibrariesRoute: SetupLibrariesRoute,
  SetupProfileRoute: SetupProfileRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MediaRoute: MediaRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  SetupRoute: SetupRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
